name: Build Self-Hosted PHP Binary (bulk)

on:
  workflow_dispatch:

jobs:
  build-release-artifacts:
    name: "Build ${{ matrix.php-version }} on ${{ matrix.operating-system }}"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        operating-system:
          - "ubuntu-latest"
          - "macos-latest"
          - "debian-arm64-self-hosted"
          - "macos-arm64-self-hosted"
        extensions:
          - apcu,bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,intl,mbstring,mbregex,mysqli,mysqlnd,openssl,opcache,pcntl,pdo,pdo_mysql,pdo_sqlite,pdo_pgsql,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib,bz2,event,gmp,imagick,imap,ldap,protobuf,shmop,snappy,soap,swoole,sysvmsg,sysvsem,sysvshm,tidy,zstd
    
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: OS type
        id: os-type
        run: |
          OS=""
          if [ "${{ matrix.operating-system }}" = "ubuntu-latest" ]; then
              OS="linux-x86_64"
          elif [ "${{ matrix.operating-system }}" = "macos-latest" ]; then
              OS="macos-x86_64"
          elif [ "${{ matrix.operating-system }}" = "debian-arm64-self-hosted" ]; then
              OS="linux-aarch64"
          elif [ "${{ matrix.operating-system }}" = "macos-arm64-self-hosted" ]; then
              OS="macos-aarch64"
          fi
          echo "OS=$OS" >> $GITHUB_ENV

      - name: Download SPC bin artifact for self-hosted runners
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: static-php/static-php-cli-hosted
          branch: master
          workflow: build-spc-release.yml
          name: "spc-${{ env.OS }}"

      - name: Validate SPC bin
        run: |
          chmod +x spc
          ./spc --version

      - id: cache-download
        uses: actions/cache@v3
        with:
          path: downloads
          key: php-${{ matrix.php-version }}-dependencies-for-bulk-extensions
      
      # If there's no dependencies cache, fetch sources
      - if: steps.cache-download.outputs.cache-hit != 'true'
        name: "Download sources"
        env:
          GITHUB_TOKEN: ${{ secrets.S_GITHUB_TOKEN }}
        run: ./spc download --with-php=${{ matrix.php-version }} --for-extensions=${{ matrix.extensions }}

      - name: "Build library: ${{ matrix.library }}"
        run: |
          SPC_USE_SUDO=yes ./spc doctor --auto-fix
          ./spc build --build-cli --build-micro --build-fpm ${{ matrix.extensions }} --debug
          PHPVER=$(cat source/php-src/main/php_version.h | grep "PHP_VERSION " | awk -F\" '{print $2}')
          mkdir dist/
          tar -czf dist/php-$PHPVER-cli-$OS.tar.gz -C buildroot/bin/ php
          tar -czf dist/php-$PHPVER-micro-$OS.tar.gz -C buildroot/bin/ micro.sfx
          tar -czf dist/php-$PHPVER-fpm-$OS.tar.gz -C buildroot/bin/ php-fpm

      - name: Deploy to Zhamao Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_SECRET_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_SERVER_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
          TARGET: ${{ secrets.DEPLOY_SERVER_TARGET }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: php-${{ matrix.php-version }}-${{ env.OS }}
          path: |
            buildroot/bin/php
            buildroot/bin/php-fpm
            buildroot/bin/micro.sfx
          if-no-files-found: error
